version: '2'
services:
  core:
    container_name: core
    image: custom_core
    build: ./docker/core
    tty: true
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/app 