version: '2'
services:
  web:
    image: nginx
    ports:
      - "81:81"
    links:
      - core
    extra_hosts:
      - "ng:127.0.0.1"
  
  ng:
    container_name: ng
    image: custom_ng
    build: ./docker/ng/
    tty: true
    ports:
      - "4200:4201"
    volumes:
      - ./frontend:/app

  core:
    container_name: core
    image: custom_core
    build: ./docker/core
    tty: true
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/app 