version: '3.4'
services:
  core:
    container_name: core
    image: custom_core
    build: ./docker/core
    tty: true
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/app
 
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: zobor
      POSTGRES_PASSWORD: 1234
    volumes:
      -  ./database:/var/lib/postgresql/data